name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 1
      id: test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 1
        setup-command: g++ Lab3.cpp -o Lab3
        command: "./Lab3"
        input: '32780'
        expected-output: |-
          Retroactive pay due is $1245.64
          New annual salary is $35271.28
          New monthly salary is $2939.27
        comparison-method: contains
        timeout: 1
        max-score: 5
    - name: Test 2
      id: test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 2
        setup-command: g++ Lab3.cpp -o Lab3
        command: "./Lab3"
        input: '52500'
        expected-output: |-
          Retroactive pay due is $1995.00
          New annual salary is $56490.00
          New monthly salary is $4707.50
        comparison-method: contains
        timeout: 1
        max-score: 5
    - name: Test 3
      id: test-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 3
        setup-command: g++ Lab3.cpp -o Lab3
        command: "./Lab3"
        input: '88250'
        expected-output: |-
          Retroactive pay due is $3353.50
          New annual salary is $94957.00
          New monthly salary is $7913.08
        comparison-method: contains
        timeout: 1
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-1_RESULTS: "${{steps.test-1.outputs.result}}"
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
        TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
      with:
        runners: test-1,test-2,test-3
